### ISSUE TITLE
New version 2.9.5

### ISSUE THREAD

**Issue by scoder** [winlibs/libxml2#3]
Version 2.9.5 was freshly released and there is a new release schedule. The plan is to release "whatever is there" more or less each month. Would be great if the winlibs could follow somehow.

**Comment by weltling** [comment]
Thanks for the ping, i'll check it next days. Apart from that, the updates are always followed on any libs, but the balance is also kept for stability.

Thanks.

**Comment by weltling** [comment]
I've just tagged 2.9.5. The bins can be fetched from windows.php.net, as usual. In staging now.

Thanks.
