### ISSUE TITLE
New version 2.9.7

### ISSUE THREAD

**Issue by Jan-E** [winlibs/libxml2#4]
@weltling: They seem to have an active maintenance policy now:
http://xmlsoft.org/news.html

**Comment by Jan-E** [comment]
@weltling And libxslt releases on the same day and is now at 1.1.32

**Comment by weltling** [comment]
Thanks for the info, @Jan-E. I saw that already with #3. I just spent quite some time on ICU >= 58 compat and we're now heading to the 7.2 final, so not sure it'll happen this year.

Thanks.

**Comment by Jan-E** [comment]
Fine with me. Note that the 2.9.7 release has more Windows specific changes than usual. See the http://xmlsoft.org/news.html

**Comment by weltling** [comment]
Yeah, i just went through some of the patches - the most important with 64-bit pointer truncation was patched in this repo for long already. The others are more like cleanups, so need to be tested good. One note yet is 7.0 goes into security only phase almost at the same time 7.2 goes GA. One more reason to keep things stable for now. The last staging portion that comes out with current RCs is going to be included into finals, then one can move forward at some later point.

Thanks.
